class game_hltb:
    def __init__(self, entry):
        self.game_id = entry.game_id
        self.game_name = entry.game_name
        self.game_alias = entry.game_alias
        self.game_type = entry.game_type
        self.game_image_url = entry.game_image_url
        self.game_web_link = entry.game_web_link
        self.review_score = entry.review_score
        self.profile_dev = entry.profile_dev
        self.profile_platforms = entry.profile_platforms
        self.release_world = entry.release_world
        self.similarity = entry.similarity
        self.json_content = entry.json_content
        self.main_story = entry.main_story
        self.main_extra = entry.main_extra
        self.completionist = entry.completionist
        self.all_styles = entry.all_styles
        self.coop_time = entry.coop_time
        self.mp_time = entry.mp_time
        self.complexity_lvl_combine = entry.complexity_lvl_combine
        self.complexity_lvl_sp = entry.complexity_lvl_sp
        self.complexity_lvl_co = entry.complexity_lvl_co
        self.complexity_lvl_mp = entry.complexity_lvl_mp
